[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; 1. Particije (obavezno za SensESP)
board_build.partitions = huge_app.csv

; 2. Prisilno traženje zavisnosti (RJEŠAVA TVOJU GREŠKU)
lib_ldf_mode = deep+

; 3. C++ Standard i Debug
build_unflags = -std=gnu++11
build_flags =
    -std=gnu++17
    -D CORE_DEBUG_LEVEL=3

lib_deps =
    signalk/SensESP @ ^3.3.0
    mathieucarbou/ESPAsyncWebServer @ ^3.6.0
    mathieucarbou/AsyncTCP @ ^3.3.2
    ; Eksplicitno dodajemo osnovne biblioteke da izbjegnemo "No such file"
    WiFi
    FS
    Update
